# Centralized constants

# Database configuration
DB_NAME = "game_database.db"

# Account roles - must match CHECK constraint in database
ROLE_STUDENT = "Student"
ROLE_TEACHER = "Teacher"
VALID_ROLES = [ROLE_STUDENT, ROLE_TEACHER]

# Tree health statuses - must match CHECK constraint in database
HEALTH_DEAD = "Dead"
HEALTH_WITHERED = "Withered"
HEALTH_UNHEALTHY = "Unhealthy"
HEALTH_HEALTHY = "Healthy"
VALID_HEALTH_STATUSES = [HEALTH_DEAD, HEALTH_WITHERED, HEALTH_UNHEALTHY, HEALTH_HEALTHY]

# Event types - must match CHECK constraint in database
EVENT_BONUS = "Bonus"
EVENT_PENALTY = "Penalty"
EVENT_LEVEL = "Level"
EVENT_NEUTRAL = "Neutral"
VALID_EVENT_TYPES = [EVENT_LEVEL, EVENT_BONUS, EVENT_PENALTY, EVENT_NEUTRAL]

# Resources - must match CHECK constraint in database
RESOURCE_WATER = "Water"
RESOURCE_EARTH = "Earth"
RESOURCE_SUN = "Sun"
RESOURCE_NONE = "None"
RESOURCE_ALL = "All"
VALID_RESOURCES = [RESOURCE_WATER, RESOURCE_EARTH, RESOURCE_SUN, RESOURCE_NONE, RESOURCE_ALL]

# RESOURCE MAX LEVEL
RESOURCE_MAX_LEVEL = 100
RESOURCE_MIN_LEVEL = 0

# Question types - must match CHECK constraint in database
QUESTION_MCQ = "MCQ"
QUESTION_FREE_RESPONSE = "FreeResponse"
QUESTION_MULTI_SELECT = "MultiSelect"
VALID_QUESTION_TYPES = [QUESTION_MCQ, QUESTION_FREE_RESPONSE, QUESTION_MULTI_SELECT]

# Question resource types
QUESTION_RESOURCE_WATER = "Water"
QUESTION_RESOURCE_EARTH = "Earth"
QUESTION_RESOURCE_SUN = "Sun"
QUESTION_RESOURCE_GENERAL = "General"  # For all of them.
QUESTION_RESOURCE_NONE = "None"  # For questions that don't affect resources.
VALID_QUESTION_RESOURCE_TYPES = [QUESTION_RESOURCE_WATER, QUESTION_RESOURCE_EARTH, QUESTION_RESOURCE_SUN, QUESTION_RESOURCE_GENERAL, QUESTION_RESOURCE_NONE]

# Resources awarded for question attempts
ATTEMPT_RESOURCE_WATER = "Water"
ATTEMPT_RESOURCE_EARTH = "Earth"
ATTEMPT_RESOURCE_SUN = "Sun"
ATTEMPT_RESOURCE_NONE = "None"
VALID_ATTEMPT_RESOURCES = [ATTEMPT_RESOURCE_WATER, ATTEMPT_RESOURCE_EARTH, ATTEMPT_RESOURCE_SUN, ATTEMPT_RESOURCE_NONE]
